package com.wx.community.service;
import com.wx.community.domain.*; import com.wx.community.mapper.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.UUID;
@Service public class CommunityService {
 public final UserMapper users; public final ActivityMapper activities; public final ProductMapper products; public final OrderMapper orders; public final PointLogMapper logs; public final CheckInMapper checks;
 public CommunityService(UserMapper u,ActivityMapper a,ProductMapper p,OrderMapper o,PointLogMapper l,CheckInMapper c){users=u;activities=a;products=p;orders=o;logs=l;checks=c;}
 public User user(Long id){return users.findById(id);} public List<Activity> activities(){return activities.published();} public Activity activity(Long id){return activities.find(id);} public List<Product> products(){return products.onSale();} public Product product(Long id){return products.find(id);} public List<Order> orders(Long uid){return orders.byUser(uid);} public List<PointLog> points(Long uid){return logs.byUser(uid);}
 @Transactional public User adjustPoints(Long id,int delta,String type,String remark){ if(users.adjustPoints(id,delta)!=1) throw new IllegalStateException("积分不足或用户不存在"); User u=users.findById(id); PointLog p=new PointLog(); p.userId=id;p.amount=delta;p.balance=u.points;p.type=type;p.remark=remark;logs.insert(p);return u; }
 @Transactional public void dailyCheckIn(Long uid){LocalDate d=LocalDate.now(ZoneId.of("Asia/Shanghai")); if(checks.exists(uid,d)>0) throw new IllegalStateException("今日已签到"); checks.insert(uid,d); adjustPoints(uid,1,"DAILY_CHECKIN","每日签到");}
 @Transactional public Order exchange(Long uid,Long pid){Product p=products.find(pid); if(p==null||p.pointsCost==null) throw new IllegalStateException("商品不存在"); User u=users.findById(uid); if(u==null||u.points<p.pointsCost) throw new IllegalStateException("积分不足"); if(products.lockStock(pid)!=1) throw new IllegalStateException("库存不足"); adjustPoints(uid,-p.pointsCost,"EXCHANGE","兑换商品:"+p.name); Order o=new Order();o.orderNo="WX"+System.currentTimeMillis()+UUID.randomUUID().toString().substring(0,6);o.userId=uid;o.productId=pid;o.points=p.pointsCost;o.expireAt=LocalDateTime.now().plusDays(30);orders.insert(o);return o;}
}
