package com.wx.community.controller;
import com.fasterxml.jackson.databind.ObjectMapper; import com.wx.community.api.*; import com.wx.community.security.*; import com.wx.community.service.PlatformService;
import org.springframework.jdbc.core.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;
import java.sql.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/admin") public class AdminController {
 private final JdbcTemplate db; private final PlatformService s; private final TokenService tokens; private final PasswordEncoder passwords; private final ObjectMapper json;
 public AdminController(JdbcTemplate d,PlatformService s,TokenService t,PasswordEncoder p,ObjectMapper j){db=d;this.s=s;tokens=t;passwords=p;json=j;}
 @PostMapping("/auth/login") public ApiResponse<?> login(@RequestBody Map<String,Object>b){List<Map<String,Object>>r=db.queryForList("select * from admins where username=? and status='ACTIVE'",b.get("username"));if(r.isEmpty()||!passwords.matches(String.valueOf(b.get("password")),String.valueOf(r.get(0).get("password_hash"))))throw new BusinessException("LOGIN_FAILED","账号或密码错误");Long id=((Number)r.get(0).get("id")).longValue();db.update("update admins set last_login_at=now() where id=?",id);return ApiResponse.ok(Map.of("token",tokens.issue("ADMIN",id),"username",r.get(0).get("username")));}
 @GetMapping("/dashboard") public ApiResponse<?> dashboard(){return ApiResponse.ok(Map.of("users",scalar("select count(*) from users"),"activities",scalar("select count(*) from activities"),"orders",scalar("select count(*) from orders"),"pointsIssued",scalar("select coalesce(sum(amount),0) from point_logs where amount>0")));}
 @GetMapping("/users") public ApiResponse<?> users(@RequestParam(defaultValue="")String phone){return ApiResponse.ok(db.queryForList("select id,nickname,avatar_url,phone,points,status,created_at from users where (?='' or phone=?) order by id desc limit 500",phone,phone));}
 @GetMapping("/users/{id}") public ApiResponse<?> user(@PathVariable Long id){Map<String,Object>m=new LinkedHashMap<>(db.queryForMap("select * from users where id=?",id));m.put("activities",db.queryForList("select p.*,a.title from activity_participations p join activities a on a.id=p.activity_id where p.user_id=?",id));m.put("questionnaires",db.queryForList("select r.*,q.name from questionnaire_responses r join questionnaires q on q.id=r.questionnaire_id where r.user_id=?",id));m.put("checkins",db.queryForList("select * from daily_checkins where user_id=? order by check_date desc",id));m.put("orders",s.orders(id));m.put("points",s.pointLogs(id));return ApiResponse.ok(m);}
 @PostMapping("/users/{id}/points") public ApiResponse<?> adjust(@PathVariable Long id,@AuthenticationPrincipal AuthUser a,@RequestBody Map<String,Object>b){int delta=Integer.parseInt(String.valueOf(b.get("delta")));String reason=String.valueOf(b.getOrDefault("reason","管理员调整"));return ApiResponse.ok(s.adminAdjust(id,delta,reason,a.id()));}
 @GetMapping("/activities") public ApiResponse<?> activities(){return ApiResponse.ok(db.queryForList("select a.*,(select count(*) from activity_participations p where p.activity_id=a.id) registrations,(select count(*) from activity_participations p where p.activity_id=a.id and p.status='CHECKED_IN') checkins from activities a order by id desc"));}
 @PostMapping("/activities") public ApiResponse<?> createActivity(@RequestBody Map<String,Object>b){Long id=insert("insert into activities(title,cover_url,description,signup_start,signup_end,start_time,end_time,points,place_name,address,latitude,longitude,status) values(?,?,?,?,?,?,?,100,?,?,?,?,?)",b,"title","coverUrl","description","signupStart","signupEnd","startTime","endTime","placeName","address","latitude","longitude","status");return ApiResponse.ok(db.queryForMap("select * from activities where id=?",id));}
 @PutMapping("/activities/{id}") public ApiResponse<?> updateActivity(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update activities set title=?,cover_url=?,description=?,signup_start=?,signup_end=?,start_time=?,end_time=?,points=100,place_name=?,address=?,latitude=?,longitude=?,status=? where id=?",v(b,"title"),v(b,"coverUrl"),v(b,"description"),v(b,"signupStart"),v(b,"signupEnd"),v(b,"startTime"),v(b,"endTime"),v(b,"placeName"),v(b,"address"),v(b,"latitude"),v(b,"longitude"),v(b,"status"),id);return ApiResponse.ok(db.queryForMap("select * from activities where id=?",id));}
 @GetMapping("/activities/{id}/participants") public ApiResponse<?> participants(@PathVariable Long id){return ApiResponse.ok(db.queryForList("select p.*,u.nickname,u.phone from activity_participations p join users u on u.id=p.user_id where p.activity_id=? order by p.registered_at",id));}
 @GetMapping("/activities/{id}/qr") public ApiResponse<?> qr(@PathVariable Long id){return ApiResponse.ok(Map.of("token",s.qrToken(id),"expiresIn",60));}
 @PostMapping("/activities/{aid}/participants/{uid}/check-in") public ApiResponse<?> manual(@PathVariable Long aid,@PathVariable Long uid){return ApiResponse.ok(s.manualCheckIn(uid,aid));}
 @GetMapping("/questionnaires") public ApiResponse<?> questionnaires(){return ApiResponse.ok(db.queryForList("select q.*,(select count(*) from questionnaire_responses r where r.questionnaire_id=q.id) submissions from questionnaires q order by id desc"));}
 @GetMapping("/questionnaires/{id}") public ApiResponse<?> questionnaireDetail(@PathVariable Long id){Map<String,Object> q=new LinkedHashMap<>(db.queryForMap("select * from questionnaires where id=?",id));q.put("questions",db.queryForList("select * from questionnaire_questions where questionnaire_id=? order by sort_order,id",id));return ApiResponse.ok(q);}
 @PostMapping("/questionnaires") public ApiResponse<?> questionnaire(@RequestBody Map<String,Object>b){Long id=insert("insert into questionnaires(name,description,start_time,end_time,reward_points,status,pinned) values(?,?,?,?,100,?,false)",b,"name","description","startTime","endTime","status");replaceQuestions(id,(List<?>)b.getOrDefault("questions",List.of()));return ApiResponse.ok(db.queryForMap("select * from questionnaires where id=?",id));}
 @PutMapping("/questionnaires/{id}") public ApiResponse<?> questionnaireUpdate(@PathVariable Long id,@RequestBody Map<String,Object>b){if(scalar("select count(*) from questionnaire_responses where questionnaire_id="+id).intValue()>0&&b.containsKey("questions"))throw new BusinessException("QUESTIONNAIRE_LOCKED","已有答卷，不能修改题目");db.update("update questionnaires set name=?,description=?,start_time=?,end_time=?,reward_points=100,status=? where id=?",v(b,"name"),v(b,"description"),v(b,"startTime"),v(b,"endTime"),v(b,"status"),id);if(b.containsKey("questions"))replaceQuestions(id,(List<?>)b.get("questions"));return ApiResponse.ok(db.queryForMap("select * from questionnaires where id=?",id));}
 @PostMapping("/questionnaires/{id}/pin") public ApiResponse<?> pin(@PathVariable Long id){db.update("update questionnaires set pinned=false");db.update("update questionnaires set pinned=true where id=? and status='PUBLISHED'",id);return ApiResponse.ok(true);}
 @GetMapping("/questionnaires/{id}/responses") public ApiResponse<?> responses(@PathVariable Long id){return ApiResponse.ok(db.queryForList("select r.*,u.nickname,u.phone from questionnaire_responses r join users u on u.id=r.user_id where r.questionnaire_id=? order by submitted_at desc",id));}
 @GetMapping("/products") public ApiResponse<?> products(){return ApiResponse.ok(db.queryForList("select * from products order by id desc"));}
 @PostMapping("/products") public ApiResponse<?> product(@RequestBody Map<String,Object>b){Long id=insert("insert into products(name,cover_url,description,points_cost,stock,status) values(?,?,?,?,?,?)",b,"name","coverUrl","description","pointsCost","stock","status");return ApiResponse.ok(db.queryForMap("select * from products where id=?",id));}
 @PutMapping("/products/{id}") public ApiResponse<?> productUpdate(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update products set name=?,cover_url=?,description=?,points_cost=?,status=? where id=?",v(b,"name"),v(b,"coverUrl"),v(b,"description"),v(b,"pointsCost"),v(b,"status"),id);return ApiResponse.ok(db.queryForMap("select * from products where id=?",id));}
 @PostMapping("/products/{id}/stock") public ApiResponse<?> stock(@PathVariable Long id,@RequestBody Map<String,Object>b){int d=Integer.parseInt(String.valueOf(b.get("delta")));if(db.update("update products set stock=stock+? where id=? and stock+?>=0",d,id,d)!=1)throw new BusinessException("INVALID_STOCK","库存不足");return ApiResponse.ok(db.queryForMap("select * from products where id=?",id));}
 @GetMapping("/orders") public ApiResponse<?> orders(){s.expireOrders();return ApiResponse.ok(db.queryForList("select o.*,u.nickname,u.phone from orders o join users u on u.id=o.user_id order by o.created_at desc"));}
 @PostMapping("/orders/{id}/pickup") public ApiResponse<?> pickup(@PathVariable Long id,@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.finishOrder(id,a.id()));}
 @PostMapping("/orders/{id}/cancel") public ApiResponse<?> cancel(@PathVariable Long id,@AuthenticationPrincipal AuthUser a,@RequestBody Map<String,Object>b){return ApiResponse.ok(s.cancelOrder(id,String.valueOf(b.get("reason")),a.id()));}
 @GetMapping("/points") public ApiResponse<?> points(){return ApiResponse.ok(db.queryForList("select l.*,u.nickname,u.phone,a.username operator_name from point_logs l join users u on u.id=l.user_id left join admins a on a.id=l.operator_admin_id order by l.created_at desc limit 2000"));}
 @GetMapping("/content") public ApiResponse<?> content(){return ApiResponse.ok(db.queryForList("select * from content_items order by content_type,sort_order,id"));}
 @PostMapping("/content") public ApiResponse<?> contentCreate(@RequestBody Map<String,Object>b){Long id=insert("insert into content_items(content_type,title,image_url,content,sort_order,enabled,activity_id,latitude,longitude,address) values(?,?,?,?,?,?,?,?,?,?)",b,"contentType","title","imageUrl","content","sortOrder","enabled","activityId","latitude","longitude","address");return ApiResponse.ok(db.queryForMap("select * from content_items where id=?",id));}
 @PutMapping("/content/{id}") public ApiResponse<?> contentUpdate(@PathVariable Long id,@RequestBody Map<String,Object>b){db.update("update content_items set title=?,image_url=?,content=?,sort_order=?,enabled=?,activity_id=?,latitude=?,longitude=?,address=? where id=?",v(b,"title"),v(b,"imageUrl"),v(b,"content"),v(b,"sortOrder"),v(b,"enabled"),v(b,"activityId"),v(b,"latitude"),v(b,"longitude"),v(b,"address"),id);return ApiResponse.ok(db.queryForMap("select * from content_items where id=?",id));}
 private void replaceQuestions(Long id,List<?> qs){db.update("delete from questionnaire_questions where questionnaire_id=?",id);int i=0;for(Object x:qs){Map<?,?>q=(Map<?,?>)x;Object options=q.containsKey("options")?q.get("options"):List.of();Object required=q.containsKey("required")?q.get("required"):Boolean.TRUE;try{db.update("insert into questionnaire_questions(questionnaire_id,question_type,title,options_json,required,sort_order) values(?,?,?,?,?,?)",id,q.get("questionType"),q.get("title"),json.writeValueAsString(options),required,i++);}catch(Exception e){throw new BusinessException("INVALID_QUESTION","题目格式错误");}}}
 private Long insert(String sql,Map<String,Object>b,String...keys){org.springframework.jdbc.support.GeneratedKeyHolder h=new org.springframework.jdbc.support.GeneratedKeyHolder();db.update(c->{PreparedStatement p=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);for(int i=0;i<keys.length;i++)p.setObject(i+1,v(b,keys[i]));return p;},h);return Objects.requireNonNull(h.getKey()).longValue();}
 private Object v(Map<String,Object>b,String k){return b.get(k);} private Number scalar(String sql){return db.queryForObject(sql,Number.class);}
}
