package com.wx.community.controller;
import com.google.zxing.*; import com.google.zxing.client.j2se.MatrixToImageWriter; import com.google.zxing.common.BitMatrix; import com.wx.community.api.*; import com.wx.community.service.PlatformService;
import org.springframework.beans.factory.annotation.Value; import org.springframework.core.io.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
import java.io.*; import java.nio.file.*; import java.util.*;
@RestController @RequestMapping("/api/admin") public class AssetController {
 private final Path root; private final String base; private final JdbcTemplate db; private final PlatformService platform;
 public AssetController(@Value("${app.upload-dir:./uploads}")String root,@Value("${app.public-base-url:http://localhost:8081}")String base,JdbcTemplate db,PlatformService platform)throws IOException{this.root=Path.of(root).toAbsolutePath().normalize();this.base=base;this.db=db;this.platform=platform;Files.createDirectories(this.root);}
 @PostMapping(value="/uploads",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ApiResponse<?> upload(@RequestPart("file")MultipartFile file)throws IOException{if(file.isEmpty())throw new BusinessException("EMPTY_FILE","请选择文件");String ext=Optional.ofNullable(file.getOriginalFilename()).filter(x->x.contains(".")).map(x->x.substring(x.lastIndexOf('.'))).orElse("");String key=UUID.randomUUID()+ext.replaceAll("[^.A-Za-z0-9]","");Path target=root.resolve(key);file.transferTo(target);String url=base+"/uploads/"+key;db.update("insert into file_assets(original_name,storage_key,public_url,content_type,size_bytes) values(?,?,?,?,?)",file.getOriginalFilename(),key,url,file.getContentType(),file.getSize());return ApiResponse.ok(Map.of("url",url,"name",file.getOriginalFilename()));}
 @GetMapping(value="/activities/{id}/qr.png",produces=MediaType.IMAGE_PNG_VALUE) public byte[] qr(@PathVariable Long id)throws Exception{String token=platform.qrToken(id);BitMatrix matrix=new MultiFormatWriter().encode(token,BarcodeFormat.QR_CODE,420,420);ByteArrayOutputStream out=new ByteArrayOutputStream();MatrixToImageWriter.writeToStream(matrix,"PNG",out);return out.toByteArray();}
 @GetMapping("/exports/{resource}") public ResponseEntity<byte[]> export(@PathVariable String resource)throws Exception{List<Map<String,Object>> rows=switch(resource){case "participants"->db.queryForList("select p.*,u.nickname,u.phone,a.title activity_title from activity_participations p join users u on u.id=p.user_id join activities a on a.id=p.activity_id order by p.registered_at desc");case "responses"->db.queryForList("select r.*,u.nickname,u.phone,q.name questionnaire_name from questionnaire_responses r join users u on u.id=r.user_id join questionnaires q on q.id=r.questionnaire_id order by r.submitted_at desc");default->db.queryForList("select l.*,u.nickname,u.phone from point_logs l join users u on u.id=l.user_id order by l.created_at desc");};org.apache.poi.xssf.usermodel.XSSFWorkbook book=new org.apache.poi.xssf.usermodel.XSSFWorkbook();var sheet=book.createSheet(resource);if(!rows.isEmpty()){List<String>keys=new ArrayList<>(rows.get(0).keySet());var head=sheet.createRow(0);for(int i=0;i<keys.size();i++)head.createCell(i).setCellValue(keys.get(i));for(int r=0;r<rows.size();r++){var row=sheet.createRow(r+1);for(int i=0;i<keys.size();i++)row.createCell(i).setCellValue(String.valueOf(rows.get(r).getOrDefault(keys.get(i),"")));}}ByteArrayOutputStream out=new ByteArrayOutputStream();book.write(out);book.close();return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename="+resource+".xlsx").body(out.toByteArray());}
}
