package com.wx.community.controller;
import com.wx.community.api.*; import com.wx.community.security.*; import com.wx.community.service.PlatformService;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.client.RestClient;
import java.util.*;
@RestController @RequestMapping("/api") public class MiniController {
 private final PlatformService s; private final TokenService tokens; private final JdbcTemplate db; private final boolean dev; private final String appId,appSecret;
 public MiniController(PlatformService s,TokenService t,JdbcTemplate db,@Value("${app.dev-auth-enabled:true}")boolean dev,@Value("${app.wechat.app-id:}")String appId,@Value("${app.wechat.app-secret:}")String appSecret){this.s=s;this.tokens=t;this.db=db;this.dev=dev;this.appId=appId;this.appSecret=appSecret;}
 @PostMapping("/dev/auth/mock") public ApiResponse<?> mock(@RequestBody Map<String,Object>b){if(!dev)throw new BusinessException("DEV_AUTH_DISABLED","模拟登录未启用");String openid="dev:"+b.getOrDefault("openid","demo");Map<String,Object>u=s.createOrUpdateUser(openid,str(b,"nickname","测试用户"),str(b,"avatarUrl",null),str(b,"phone","13800000000"));return ApiResponse.ok(auth(u));}
 @PostMapping("/mini/auth/wechat") public ApiResponse<?> wechat(@RequestBody Map<String,Object>b){if(appId.isBlank()||appSecret.isBlank())throw new BusinessException("WECHAT_NOT_CONFIGURED","微信登录尚未配置，请使用开发模拟登录");String code=str(b,"code","");Map<?,?> wx=RestClient.create().get().uri("https://api.weixin.qq.com/sns/jscode2session?appid={a}&secret={s}&js_code={c}&grant_type=authorization_code",appId,appSecret,code).retrieve().body(Map.class);if(wx==null||wx.get("openid")==null)throw new BusinessException("WECHAT_LOGIN_FAILED","微信登录失败");Map<String,Object>u=s.createOrUpdateUser(String.valueOf(wx.get("openid")),str(b,"nickname",null),str(b,"avatarUrl",null),str(b,"phone",null));return ApiResponse.ok(auth(u));}
 @PostMapping("/mini/auth/profile") public ApiResponse<?> profileUpdate(@AuthenticationPrincipal AuthUser a,@RequestBody Map<String,Object>b){Map<String,Object>u=s.createOrUpdateUser((String)db.queryForMap("select openid from users where id=?",a.id()).get("openid"),str(b,"nickname",null),str(b,"avatarUrl",null),str(b,"phone",null));return ApiResponse.ok(auth(u));}
 @PostMapping("/mini/auth/phone") public ApiResponse<?> bindPhone(@AuthenticationPrincipal AuthUser a,@RequestBody Map<String,Object>b){
  Long uid=required(a);if(appId.isBlank()||appSecret.isBlank())throw new BusinessException("WECHAT_NOT_CONFIGURED","微信手机号授权尚未配置");String phoneCode=str(b,"code","");if(phoneCode.isBlank())throw new BusinessException("PHONE_CODE_REQUIRED","请授权手机号");
  Map<?,?> access=RestClient.create().get().uri("https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={a}&secret={s}",appId,appSecret).retrieve().body(Map.class);Object accessToken=access==null?null:access.get("access_token");if(accessToken==null)throw new BusinessException("WECHAT_PHONE_FAILED","微信手机号授权失败");
  Map<?,?> result=RestClient.create().post().uri("https://api.weixin.qq.com/wxa/business/getuserphonenumber?access_token={t}",accessToken).contentType(MediaType.APPLICATION_JSON).body(Map.of("code",phoneCode)).retrieve().body(Map.class);Object info=result==null?null:result.get("phone_info");if(!(info instanceof Map<?,?> phoneInfo)||phoneInfo.get("phoneNumber")==null)throw new BusinessException("WECHAT_PHONE_FAILED","微信手机号授权失败");
  String openid=String.valueOf(db.queryForMap("select openid from users where id=?",uid).get("openid"));Map<String,Object>u=s.createOrUpdateUser(openid,null,null,String.valueOf(phoneInfo.get("phoneNumber")));return ApiResponse.ok(auth(u));
 }
 @GetMapping("/mini/home") public ApiResponse<?> home(@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.home(uid(a)));}
 @GetMapping("/mini/activities") public ApiResponse<?> activities(@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.activities(uid(a)));}
 @GetMapping("/mini/activities/{id}") public ApiResponse<?> activity(@PathVariable Long id,@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.activity(id,uid(a)));}
 @PostMapping("/mini/activities/{id}/register") public ApiResponse<?> register(@PathVariable Long id,@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.registerActivity(registered(a),id));}
 @PostMapping("/mini/activities/verify") public ApiResponse<?> verify(@AuthenticationPrincipal AuthUser a,@RequestBody Map<String,Object>b){return ApiResponse.ok(s.verifyActivity(registered(a),str(b,"token",""),"QR"));}
 @GetMapping("/mini/check-ins") public ApiResponse<?> checkins(@AuthenticationPrincipal AuthUser a,@RequestParam(defaultValue="0")int year,@RequestParam(defaultValue="0")int month){var now=java.time.LocalDate.now(java.time.ZoneId.of("Asia/Shanghai"));return ApiResponse.ok(s.checkinSummary(required(a),year==0?now.getYear():year,month==0?now.getMonthValue():month));}
 @PostMapping("/mini/check-ins") public ApiResponse<?> checkin(@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.dailyCheckIn(registered(a)));}
 @GetMapping("/mini/questionnaires/active") public ApiResponse<?> questionnaire(@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.activeQuestionnaire(required(a)));}
 @PostMapping("/mini/questionnaires/{id}/submit") public ApiResponse<?> submit(@PathVariable Long id,@AuthenticationPrincipal AuthUser a,@RequestBody Map<String,Object>b){return ApiResponse.ok(s.submitQuestionnaire(registered(a),id,b.get("answers")));}
 @GetMapping("/mini/products") public ApiResponse<?> products(){return ApiResponse.ok(s.products());}
 @GetMapping("/mini/products/{id}") public ApiResponse<?> product(@PathVariable Long id){return ApiResponse.ok(s.product(id));}
 @PostMapping("/mini/orders") public ApiResponse<?> exchange(@AuthenticationPrincipal AuthUser a,@RequestBody Map<String,Object>b,@RequestHeader(value="Idempotency-Key",required=false)String key){String request=key==null?str(b,"requestId",UUID.randomUUID().toString()):key;return ApiResponse.ok(s.exchange(registered(a),Long.valueOf(String.valueOf(b.get("productId"))),request));}
 @GetMapping("/mini/orders") public ApiResponse<?> orders(@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.orders(required(a)));}
 @GetMapping("/mini/profile") public ApiResponse<?> profile(@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.profile(required(a)));}
 @GetMapping("/mini/profile/points") public ApiResponse<?> points(@AuthenticationPrincipal AuthUser a){return ApiResponse.ok(s.pointLogs(required(a)));}
 @GetMapping("/mini/content/{type}") public ApiResponse<?> content(@PathVariable String type){return ApiResponse.ok(s.content(type.toUpperCase(Locale.ROOT)));}
 private Map<String,Object>auth(Map<String,Object>u){return Map.of("token",tokens.issue("USER",((Number)u.get("id")).longValue()),"user",u,"needsPhone",u.get("phone")==null);}
 private Long uid(AuthUser a){return a!=null&&"USER".equals(a.role())?a.id():null;} private Long required(AuthUser a){Long id=uid(a);if(id==null)throw new BusinessException("LOGIN_REQUIRED","请先登录");return id;} private Long registered(AuthUser a){Long id=required(a);Object phone=db.queryForObject("select phone from users where id=?",Object.class,id);if(phone==null||String.valueOf(phone).isBlank())throw new BusinessException("PHONE_REQUIRED","请先授权手机号完成注册");return id;}
 private String str(Map<String,Object>b,String k,String d){Object v=b.get(k);return v==null?d:String.valueOf(v);}
}
