const miniMeta={
 home:['首页 · 用户入口','首屏用蓝粉双色品牌视觉承接活动横幅、快捷入口与关于我们内容。'],
 activities:['活动列表 · 状态优先','可报名和进行中的活动优先展示；卡片保留活动状态标签。'],
 'activity-detail':['活动详情 · 报名与签到','时间、地点、奖励积分和活动内容集中呈现；底部按钮随状态变化。'],
 'product-detail':['商品详情 · 积分兑换','查看商品信息、领取地址和兑换规则。'],
 checkin:['每日签到 · 任务中心','展示可用积分、本月日历和问卷/线下活动任务。'],
 survey:['问卷填写 · 必填校验','单选、多选、文本题共享清晰题面；提交成功后发放奖励积分。'],
 products:['积分兑换 · 商品列表','商品使用真实库存状态，售罄仍保留展示；订单创建后进入待领取。'],
 orders:['兑换记录 · 领取凭证','订单按下单时间倒序，展示订单编号、领取期限和取消原因。'],
 points:['积分明细 · 收支记录','查看积分获得与使用的完整记录。'],
 profile:['个人中心 · 账户与记录','头像、昵称、手机号和可用积分是首要信息，记录入口按业务聚合。']
};
const activity='激情夏日·热辣滚烫';
const asset=(name,alt='')=>`<img class="original-asset" src="assets/originals/${name}" alt="${alt}" loading="eager">`;
const icon=(name)=>({calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3v4M16 3v4M4 10h16M8 14h2M14 14h2M8 17h2"/></svg>',gift:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10h18v10H3zM2 7h20v3H2zM12 7v13M12 7H7.5a2.5 2.5 0 1 1 2.3-3.5L12 7Zm0 0h4.5a2.5 2.5 0 1 0-2.3-3.5L12 7Z"/></svg>',check:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></svg>',entryActivity:'<svg viewBox="0 0 28 28"><rect x="3" y="3" width="22" height="22" rx="6" fill="#f6dfff"/><rect x="8" y="7" width="12" height="13" rx="2" fill="none" stroke="#bc65d6" stroke-width="1.8"/><path d="M11 5v4M17 5v4M8 11h12M11 15h2M15 15h2" fill="none" stroke="#bc65d6" stroke-width="1.6"/></svg>',entryPoints:'<svg viewBox="0 0 28 28"><rect x="3" y="3" width="22" height="22" rx="6" fill="#ffe0ed"/><path d="M8 9h12v11H8zM7 7h14v4H7zM14 7v13M11 7c-3-4 2-6 3 0M14 7c1-6 6-3 3 0" fill="none" stroke="#eb639e" stroke-width="1.6"/></svg>',entryCheckin:'<svg viewBox="0 0 28 28"><rect x="3" y="3" width="22" height="22" rx="6" fill="#dfe7ff"/><path d="M14 7 20 9v5c0 4-2.6 6.5-6 7-3.4-.5-6-3-6-7V9z" fill="#6d77d9"/><path d="m10.5 14 2.2 2.2 4.4-4.6" fill="none" stroke="#fff" stroke-width="1.7"/></svg>',back:'<svg viewBox="0 0 24 24"><path d="m14 5-7 7 7 7M7 12h13"/></svg>',home:'<svg viewBox="0 0 24 24"><path d="m4 11 8-7 8 7v8H4z"/><path d="M9 19v-5h6v5"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.7-4 3-6 7-6s6.3 2 7 6"/></svg>'}[name]||'');
const originalIcon=(name,alt)=>asset(name,alt);
const tabGroup=(page)=>page==='activities'||page==='activity-detail'?'activities':page==='products'||page==='product-detail'||page==='orders'?'products':page==='profile'?'profile':'home';
const tabIcon=(name,active)=>`<img class="tab-icon" src="assets/tabbar/${name}${active?'-active':''}.svg" alt="">`;
const bottomTabs=(page)=>{const active=tabGroup(page);return `<div class="drawn-tabbar"><button data-page="home" class="${active==='home'?'active':''}">${tabIcon('home',active==='home')}<small>首页</small></button><button data-page="activities" class="${active==='activities'?'active':''}">${tabIcon('activities',active==='activities')}<small>活动</small></button><button class="drawn-tab-main scan-tab" id="scan-entry"><span class="scan-glyph"><img src="assets/tabbar/scan.svg" alt="扫码"></span><small>扫码</small></button><button data-page="products" class="${active==='products'?'active':''}">${tabIcon('products',active==='products')}<small>兑换</small></button><button data-page="profile" class="${active==='profile'?'active':''}">${tabIcon('profile',active==='profile')}<small>我的</small></button></div>`};
const brandMark=()=>`<div class="brand-illustration"><span class="brand-pi">π</span><span class="brand-spark spark-a"></span><span class="brand-spark spark-b"></span><span class="brand-eye eye-a"></span><span class="brand-eye eye-b"></span></div>`;
function drawnPage(page){
 if(page==='home') return `<div class="drawn-page home-drawn"><div class="promo-banner original-banner">${asset('event-rainbow.jpg','鄞领π活动横幅')}</div><div class="hello">Hi，刘德华</div><div class="quick-drawn"><button data-page="activities">${originalIcon('icon-activity.jpg','活动报名')}<span>活动报名</span></button><button data-page="products">${originalIcon('icon-points.jpg','积分兑换')}<span>积分兑换</span></button><button data-page="checkin">${originalIcon('icon-checkin.jpg','每日签到')}<span>每日签到</span></button></div><button class="about-drawn original-about" data-page="activities">${asset('home-about.png','活动列表')}<span class="about-more">查看更多 <b>›</b></span></button><div class="drawn-modal-shade" id="home-modal"><div class="drawn-modal original-modal"><button class="drawn-modal-close" id="close-home-modal">×</button>${asset('survey-reward.jpg','填写调查问卷获得积分')}</div></div>${bottomTabs(page)}</div>`;
 if(page==='activities') return `<div class="drawn-page activities-drawn"><div class="drawn-top page-title">活动报名 <span class="top-more">•••　◉</span></div><div class="search-drawn">⌕　输入活动标题</div>${[1,2,3].map((_,i)=>`<button class="activity-drawn-card" data-page="activity-detail"><div class="activity-cover original-activity-cover">${asset('activity-orange.jpg','激情夏日热辣滚烫活动')}</div><strong>${activity}</strong><small class="activity-time">活动时间：<time>2026-09-20 14:00:00</time> - <time>2026-09-20 17:00:00</time></small></button>`).join('')}${bottomTabs(page)}</div>`;
 if(page==='products') return `<div class="drawn-page products-drawn products-hd"><div class="products-top"><span></span><span>•••　│　◎</span></div><button class="products-banner-link" data-page="activities" aria-label="参加线下活动"><img src="assets/originals/points-top-banner.png" alt="参与线下活动获取更多积分"></button><div class="products-items">${[1,2,3,4].map(()=>`<button class="product-card-link" data-page="product-detail" aria-label="查看商品详情"><img src="assets/originals/points-product-item.png" alt="潮流定制托特帆布包"></button>`).join('')}</div>${bottomTabs(page)}</div>`;
 if(page==='profile') return `<div class="drawn-page profile-reference-page"><div class="profile-reference-scroll"><img src="assets/originals/profile-top.png" alt="个人中心"><img class="profile-address" src="assets/originals/points-detail-address.png" alt="鄞领π服务点地址"><button class="profile-hotspot profile-points" data-page="points" aria-label="积分明细"></button><button class="profile-hotspot profile-orders" data-page="orders" aria-label="兑换记录"></button></div>${bottomTabs(page)}</div>`;
 if(page==='points') return `<div class="drawn-page points-ledger-page"><div class="points-ledger-top"><button data-page="profile" aria-label="返回个人中心">‹</button><strong>积分明细</strong><span>•••　│　◎</span></div><div class="points-ledger-balance"><small>当前积分</small><strong>105</strong><span>积分</span></div><section class="points-ledger-list"><div class="points-ledger-row"><b>+100</b><div><strong>填写调查问卷</strong><small>2026-09-12 10:08:00</small></div><em>调查问卷奖励</em></div><div class="points-ledger-row"><b>+10</b><div><strong>参加线下活动</strong><small>2026-09-10 15:26:00</small></div><em>活动签到奖励</em></div><div class="points-ledger-row negative"><b>-10</b><div><strong>积分兑换</strong><small>2026-09-08 14:20:00</small></div><em>潮流定制托特帆布包</em></div></section></div>`;
 if(page==='checkin') return `<div class="drawn-page checkin-drawn"><div class="drawn-top page-title"><div class="checkin-nav"><button data-page="home" aria-label="返回首页">‹</button><i></i><button data-page="home" aria-label="首页">${icon('home')}</button></div>每日签到<span class="top-more">•••　│　◎</span></div><div class="checkin-score"><small>我的积分</small><strong>1005</strong></div><div class="calendar-drawn"><b>2026年9月</b><small>已连续签到0天</small><div class="week">${['一','二','三','四','五','六','日'].map(day=>`<span>${day}</span>`).join('')}</div><div class="calendar-grid">${['31','今','2','3','4','5','6'].map((day,i)=>`<span class="${i===1?'today':i===0?'previous':''}">${day}</span>`).join('')}</div><div class="calendar-progress" aria-hidden="true"><i></i></div><button id="daily-checkin" class="orange-btn"><span>立即签到</span><small>每日签到奖励1积分</small></button></div><section class="checkin-tasks"><h2>参加活动赚积分</h2><div class="checkin-task-body"><button class="task-drawn" data-page="survey">${asset('checkin-survey.png','调查问卷')}<div><b>填写调查问卷</b><em>去填写</em></div></button><button class="task-drawn" data-page="activities">${asset('checkin-activity.png','线下活动')}<div><b>参加线下活动</b><em>去报名</em></div></button></div></section></div>`;
 if(page==='activity-detail') return `<div class="drawn-page detail-drawn"><div class="drawn-top page-title">${icon('back')}　活动详情 <span class="top-more">•••　◉</span></div><div class="detail-cover original-detail-cover">${asset('activity-orange.jpg','活动宣传')}</div><div class="detail-white"><strong>${activity}</strong><small>报名时间：2026-09-01 00:00:00 - 2026-09-18 23:59:59<br>活动时间：2026-09-20 14:00:00 - 2026-09-20 17:00:00<br>活动地点：鄞州区青年人才驿站</small></div><div class="detail-white detail-description"><b>活动详情</b><p>本次活动面向鄞州区青年人才，提供就业招聘、职业指导、技能培训、创业孵化、政策集成和生活服务等综合服务。</p><p>欢迎报名参加活动，现场签到核销后可获得活动积分。</p><p>活动现场请按工作人员指引完成签到，并保留报名凭证。</p></div><div class="detail-action"><div class="detail-reward"><strong>+10 <small>积分</small></strong><span>现场签到核销后</span></div><button id="signup">我要报名</button></div></div>`;
 if(page==='product-detail') return `<div class="drawn-page points-detail-page"><div class="points-detail-top"><button class="points-detail-back" data-page="products" aria-label="返回">‹</button><strong>积分兑换</strong><span>•••　│　◎</span></div><main class="points-detail-content"><img class="points-detail-product" src="assets/originals/points-detail-product.png" alt="潮流定制托特帆布包"><img class="points-detail-notice" src="assets/originals/points-detail-notice.png" alt="温馨提示"><img class="points-detail-address" src="assets/originals/points-detail-address.png" alt="商品领取地址"></main><div class="detail-action"><div class="detail-reward"><strong>-10 <small>积分</small></strong><span>现场扫码核销后</span></div><button id="redeem-product">我要兑换</button></div></div>`;
 return null;
}
function miniPage(page){
 const referencePages={home:'home',activities:'activities',products:'products',profile:'profile','activity-detail':'activity-detail',checkin:'checkin'};
 if(['home','activities','products','profile','checkin','activity-detail','product-detail','points'].includes(page)) return drawnPage(page);
 const body={
 home:`<div class="hero"><span class="eyebrow">鄞领π · 鄞州区大学生青年夜校</span><h1>精彩活动<br>正在发生</h1><p>报名活动 · 完成问卷 · 积分兑换好礼</p></div><div class="mini-body"><div class="greeting"><span>晚上好，<b>刘德华</b></span><span class="mini-link" data-page="profile">个人中心 →</span></div><div class="notice">✦ 置顶问卷任务 · 完成问卷可得 100 积分 <span class="mini-link" data-page="survey">立即填写</span></div><div class="quick-grid"><div class="quick" data-page="activities"><span class="qicon">▣</span>活动报名</div><div class="quick" data-page="products"><span class="qicon">▤</span>积分兑换</div><div class="quick" data-page="checkin"><span class="qicon">✓</span>每日签到</div></div><div class="section-title">关于我们 <small>查看详情 →</small></div><div class="about-card"><b>鄞领π</b><p>鄞州区大学生创新创业服务平台<br>连接青年、活动与城市生活。</p></div><div class="section-title">推荐活动 <small data-page="activities">全部活动 →</small></div><div class="task-card" data-page="activities"><span class="badge">报名中</span><h4>${activity}</h4><span class="muted">2026.09.20 · 鄞州区青年人才驿站</span></div></div><div class="modal-shade" id="survey-modal"><div class="modal"><div class="modal-cover">π</div><h3>填写调查问卷 · 得100积分</h3><p>感谢你的参与，完成问卷即可获得积分奖励。</p><button class="modal-btn" data-page="survey">去填写</button><div class="close" id="close-modal">稍后再说</div></div></div>`,
 activities:`<div class="list-head"><div class="mini-title">活动报名</div><div class="search">⌕  搜索活动标题</div></div><div class="activity-card" data-page="activity-detail"><div class="cover">激情夏日<br>热辣滚烫</div><div><span class="badge">报名中</span><h4>${activity}</h4><p class="muted">报名：09.01 - 09.18<br>活动：09.20 14:00 - 17:00</p></div></div><div class="activity-card"><div class="cover" style="background:linear-gradient(135deg,#4b8de8,#8dc9ff)">青年<br>分享会</div><div><span class="badge blue">报名未开始</span><h4>青年成长主题分享会</h4><p class="muted">报名：09.15 - 09.25<br>活动：09.28 14:00 - 16:00</p></div></div><div class="activity-card"><div class="cover" style="background:linear-gradient(135deg,#95d3a2,#55a77a)">城市<br>漫步</div><div><span class="badge green">已报名</span><h4>鄞州城市文化漫步</h4><p class="muted">活动：09.12 09:00 - 12:00</p></div></div>`,
 'activity-detail':`<div class="detail-hero"><span class="badge">报名中</span><h2>${activity}</h2><p>2026 鄞州区人才招聘会主题活动</p></div><div class="detail-card"><h3>活动信息</h3><div class="info-row">报名时间　2026.09.01 - 09.18<br>活动时间　2026.09.20 14:00 - 17:00<br>活动地点　鄞州区青年人才驿站<br>签到奖励　+10 积分</div></div><div class="detail-card"><h3>活动详情</h3><p class="muted">一起参与城市青年活动，完成线下签到即可获得积分，积分可兑换精选好礼。</p><div class="info-row">📍 宁波市鄞州区学府路 1 号 · 点击导航</div></div><div class="bottom-action"><button class="primary-btn" id="signup">我要报名</button></div>`,
 checkin:`<div class="score-card"><span>可用积分</span><strong>1005 <small>分</small></strong><span class="muted" style="color:#477ba8">完成每日签到，连续积累积分</span></div><div class="calendar"><div class="calendar-head"><span>2026年9月</span><small class="muted">已连续签到 0 天</small></div><div class="days"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span>${Array.from({length:30},(_,i)=>`<b class="${[1,3,8,10,11].includes(i)?'checked':''}">${i+1}</b>`).join('')}</div><button class="primary-btn" id="daily-checkin" style="margin-top:14px">立即签到 · +1积分</button></div><div class="section-title" style="padding:0 15px">任务中心</div><div class="task-card" data-page="survey"><span class="badge">问卷任务</span><h4>青年生活方式调查问卷</h4><span class="muted">完成可得 100 积分　→</span></div><div class="task-card" data-page="activity-detail"><span class="badge blue">线下活动</span><h4>${activity}</h4><span class="muted">报名参加可获得活动积分　→</span></div>`,
 survey:`<div class="survey-head"><span class="badge pink">问卷任务</span><h2>青年生活方式调查问卷</h2><p class="muted">了解你的真实想法，完成后奖励 100 积分</p></div><div class="question"><p>1. 你平时更关注哪些活动？<em>*</em></p><label class="option selected">◉ 文体娱乐活动</label><label class="option">○ 职业技能提升</label><label class="option">○ 志愿公益活动</label></div><div class="question"><p>2. 你希望平台增加哪些服务？</p><label class="option">□ 场地预约</label><label class="option">□ 青年社群</label><label class="option">□ 创业指导</label></div><div class="question"><p>3. 对平台的建议</p><textarea class="input" placeholder="请输入你的建议" style="width:100%;min-height:72px"></textarea></div><div class="bottom-action"><button class="primary-btn" id="submit-survey">提交问卷 · 获得100积分</button></div>`,
 products:`<div class="list-head"><div class="mini-title">积分兑换</div><div class="notice" style="margin:10px 0 0">参与线下活动，获取更多积分　<span class="mini-link" data-page="activities">去报名 →</span></div></div><div class="product-card"><div class="product-art">🎒</div><div><span class="badge green">可兑换</span><h4>潮流定制托特帆布包</h4><p class="muted">实用环保 · 鄞领π定制好礼</p><div class="price">100 积分 <span class="mini-link" data-page="orders">兑换记录 →</span></div></div></div><div class="product-card"><div class="product-art" style="background:linear-gradient(135deg,#ffd4e6,#f58ab4)">☕</div><div><span class="badge blue">可兑换</span><h4>鄞领π限定马克杯</h4><p class="muted">每日可用 · 限量 20 件</p><div class="price">80 积分</div></div></div><div class="product-card"><div class="product-art" style="background:#e6edf2;color:#94a5b2">▦</div><div><span class="badge" style="background:#9aa9b6">已兑完</span><h4>青年活动纪念徽章</h4><p class="muted">暂时无库存，敬请期待</p><div class="price" style="color:#95a4b0">50 积分</div></div></div>`,
 orders:`<div class="orders-page"><div class="orders-top"><button data-page="profile" aria-label="返回个人中心">‹</button><strong>兑换记录</strong><span>•••　│　◎</span></div><div class="order-card"><span class="badge">待领取</span><h4>潮流定制托特帆布包</h4><p class="muted">订单编号：YL202609120001<br>消耗积分：100　下单：2026.09.12 10:12<br>领取截止：2026.10.12</p><div class="notice" style="margin:9px 0 0">领取时请出示订单编号和绑定手机号</div></div><div class="order-card"><span class="badge green">已领取</span><h4>鄞领π限定马克杯</h4><p class="muted">订单编号：YL202608280023<br>消耗积分：80　领取时间：2026.09.01</p></div><div class="order-card"><span class="badge" style="background:#9aa9b6">已取消</span><h4>青年活动纪念徽章</h4><p class="muted">订单编号：YL202607110008<br>取消原因：逾期未领取　已退还 50 积分</p></div></div>`,
 profile:`<div class="profile-head"><div class="profile-row"><div class="avatar-lg">刘</div><div><h2>刘德华</h2><p>已绑定手机号 138****8888</p></div><span class="mini-link" style="margin-left:auto">重新授权</span></div><div class="profile-score"><small>可用积分</small><strong>1005</strong><small>分</small></div></div><div class="menu-list"><div class="menu-item" data-page="orders"><span>▤　兑换记录</span><span>›</span></div><div class="menu-item" data-page="checkin"><span>✓　每日签到</span><span>›</span></div><div class="menu-item"><span>∑　积分明细</span><span>›</span></div></div><div class="menu-list"><div class="menu-item"><span>积分规则</span><span>›</span></div><div class="menu-item"><span>鄞领π服务点</span><span>›</span></div><div class="menu-item"><span>关于我们</span><span>›</span></div></div>`
 };
 return body[page]||body.home;
}
function bindMini(){
 document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>setMini(el.dataset.page)));
 const pointsBack=document.querySelector('.points-detail-back'); if(pointsBack) pointsBack.onclick=(event)=>{event.preventDefault();event.stopPropagation();setMini('products')};
 const profilePoints=document.querySelector('.profile-points'); if(profilePoints) profilePoints.onclick=(event)=>{event.preventDefault();event.stopPropagation();setMini('points')};
 const detailBack=document.querySelector('.product-detail-reference-page .detail-back'); if(detailBack) detailBack.onclick=()=>setMini('products');
 const close=document.getElementById('close-modal'); if(close) close.onclick=()=>document.getElementById('survey-modal').remove();
 const homeClose=document.getElementById('close-home-modal'); if(homeClose) homeClose.onclick=()=>document.getElementById('home-modal').remove();
 const scan=document.getElementById('scan-entry'); if(scan) scan.onclick=()=>{scan.classList.add('scan-done');scan.querySelector('small').textContent='扫码中';setTimeout(()=>{scan.classList.remove('scan-done');scan.querySelector('small').textContent='扫码'},700)};
 const signup=document.getElementById('signup'); if(signup) signup.onclick=()=>{signup.textContent='已报名';signup.disabled=true;signup.style.background='#4caf88'};
 const daily=document.getElementById('daily-checkin'); if(daily) daily.onclick=()=>{daily.textContent='今日已签到';daily.disabled=true;daily.style.background='#9caebb'};
 const submit=document.getElementById('submit-survey'); if(submit) submit.onclick=()=>{submit.textContent='已完成 · 获得100积分';submit.disabled=true;submit.style.background='#4caf88'};
}
function setMini(page){const screen=document.getElementById('mini-screen');screen.innerHTML=miniPage(page);const drawn=!!screen.querySelector('.drawn-page');screen.classList.toggle('reference-active',!!screen.querySelector('.reference-page'));document.querySelector('.phone').classList.toggle('reference-phone',!!screen.querySelector('.reference-page'));document.querySelector('.phone').classList.toggle('drawn-active',drawn);document.querySelector('.phone').classList.toggle('hide-tabbar',page==='survey'||page==='orders'||page==='points');document.querySelectorAll('.page-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.getElementById('mini-title').textContent=miniMeta[page][0];document.getElementById('mini-desc').textContent=miniMeta[page][1];bindMini()}

const adminMeta={dashboard:'数据概览',users:'用户管理',events:'活动管理',surveys:'问卷管理',products:'商品与库存',orders:'兑换订单',points:'积分明细',content:'展示内容'};
function adminPage(page){
 if(page==='dashboard') return `<h1>数据概览</h1><p class="subhead">欢迎回来，以下是鄞领π平台的实时运营数据</p><div class="stat-grid"><div class="stat"><small>注册用户</small><strong>1,286</strong><span class="trend">↗ 12.6%</span></div><div class="stat"><small>本月活动参与</small><strong>428</strong><span class="trend">↗ 8.4%</span></div><div class="stat"><small>积分发放</small><strong>26,840</strong><span class="trend">↗ 18.2%</span></div><div class="stat"><small>待领取订单</small><strong>36</strong><span class="trend" style="color:#f29d45">需处理</span></div></div><div class="admin-grid"><div class="panel"><div class="panel-title">近30日积分趋势 <small>查看明细 →</small></div><div class="bar-chart">${[40,62,52,73,58,91,67,77,48,82,69,96].map((v,i)=>`<div class="bar" style="height:${v}%"><small>${i+1}日</small></div>`).join('')}</div></div><div class="panel"><div class="panel-title">最新动态 <small>全部 →</small></div><div class="activity-list"><div class="activity-row"><span class="dot"></span><div><p>刘德华完成活动签到</p><small>获得 10 积分 · 5分钟前</small></div></div><div class="activity-row"><span class="dot" style="background:#4389e9"></span><div><p>“青年生活方式问卷”已提交</p><small>新增 100 积分 · 18分钟前</small></div></div><div class="activity-row"><span class="dot" style="background:#f6a84c"></span><div><p>兑换订单 YL202609120001 创建</p><small>扣减 100 积分 · 32分钟前</small></div></div><div class="activity-row"><span class="dot" style="background:#52b990"></span><div><p>管理员发布新活动</p><small>激情夏日·热辣滚烫 · 1小时前</small></div></div></div></div></div>`;
 if(page==='users') return `<h1>用户管理</h1><p class="subhead">查询用户资料、参与记录和积分余额</p><div class="panel"><div class="table-toolbar"><input class="input" placeholder="输入手机号精确查询"/><button class="primary">查询</button><button class="ghost">导出</button></div><table class="data-table"><thead><tr><th>用户</th><th>手机号</th><th>积分余额</th><th>注册时间</th><th>账号状态</th><th>操作</th></tr></thead><tbody>${[['刘德华','138****8888','1005','2026-08-18','正常'],['王小明','139****2188','680','2026-08-21','正常'],['陈晓芸','136****6767','120','2026-08-30','正常'],['张同学','137****4098','0','2026-09-03','正常']].map((r,i)=>`<tr><td><span class="mini-avatar">${r[0][0]}</span>${r[0]}</td><td>${r[1]}</td><td><b>${r[2]}</b></td><td>${r[3]}</td><td><span class="tag green">${r[4]}</span></td><td><span class="mini-link">查看详情</span></td></tr>`).join('')}</tbody></table></div>`;
 if(page==='events') return `<h1>活动管理</h1><p class="subhead">维护活动内容、报名时间和签到配置 <button class="primary" style="float:right;padding:9px 15px">＋ 新建活动</button></p><div class="panel"><div class="table-toolbar"><input class="input" placeholder="按标题筛选"/><select class="input select"><option>全部状态</option><option>已发布</option><option>草稿</option></select><button class="primary">查询</button></div><table class="data-table"><thead><tr><th>活动标题</th><th>报名时间</th><th>活动时间</th><th>状态</th><th>报名/签到</th><th>操作</th></tr></thead><tbody><tr><td><b>${activity}</b></td><td>09.01 - 09.18</td><td>09.20 14:00</td><td><span class="tag green">已发布</span></td><td>218 / 86</td><td><span class="mini-link">编辑　参与人员</span></td></tr><tr><td><b>青年成长主题分享会</b></td><td>09.15 - 09.25</td><td>09.28 14:00</td><td><span class="tag gray">草稿</span></td><td>—</td><td><span class="mini-link">编辑</span></td></tr><tr><td><b>鄞州城市文化漫步</b></td><td>08.25 - 09.05</td><td>09.12 09:00</td><td><span class="tag blue">已发布</span></td><td>96 / 42</td><td><span class="mini-link">编辑　参与人员</span></td></tr></tbody></table></div>`;
 if(page==='products') return `<h1>商品与库存</h1><p class="subhead">维护兑换商品、上下架状态和库存变更 <button class="primary" style="float:right;padding:9px 15px">＋ 新建商品</button></p><div class="admin-card-grid"><div class="event-card"><div class="event-cover" style="background:linear-gradient(135deg,#ffe15a,#f3a536)">🎒</div><div class="event-body"><h3>潮流定制托特帆布包</h3><p>所需积分：<b>100</b></p><p>可用 48　锁定 12　已领取 86</p><div class="event-foot"><span class="tag green">已上架</span><span class="mini-link">编辑库存</span></div></div></div><div class="event-card"><div class="event-cover" style="background:linear-gradient(135deg,#ffd4e6,#f58ab4)">☕</div><div class="event-body"><h3>鄞领π限定马克杯</h3><p>所需积分：<b>80</b></p><p>可用 20　锁定 4　已领取 36</p><div class="event-foot"><span class="tag green">已上架</span><span class="mini-link">编辑库存</span></div></div></div><div class="event-card"><div class="event-cover" style="background:#dce5eb;color:#8495a3">▦</div><div class="event-body"><h3>青年活动纪念徽章</h3><p>所需积分：<b>50</b></p><p>可用 0　锁定 0　已领取 50</p><div class="event-foot"><span class="tag gray">已下架</span><span class="mini-link">编辑库存</span></div></div></div></div>`;
 if(page==='orders') return `<h1>兑换订单</h1><p class="subhead">核验线下领取、处理取消和逾期订单</p><div class="panel"><div class="table-toolbar"><input class="input" placeholder="订单编号 / 手机号"/><select class="input select"><option>全部状态</option><option>待领取</option><option>已领取</option><option>已取消</option></select><button class="primary">查询</button></div><table class="data-table"><thead><tr><th>订单编号</th><th>商品</th><th>用户</th><th>消耗积分</th><th>下单时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>YL202609120001</td><td>潮流定制托特帆布包</td><td>刘德华</td><td>100</td><td>2026-09-12 10:12</td><td><span class="tag orange">待领取</span></td><td><button class="primary" style="padding:6px 9px">确认领取</button></td></tr><tr><td>YL202609010023</td><td>鄞领π限定马克杯</td><td>王小明</td><td>80</td><td>2026-09-01 16:20</td><td><span class="tag green">已领取</span></td><td><span class="mini-link">查看详情</span></td></tr><tr><td>YL202607110008</td><td>青年活动纪念徽章</td><td>陈晓芸</td><td>50</td><td>2026-07-11 09:30</td><td><span class="tag gray">已取消</span></td><td><span class="mini-link">查看详情</span></td></tr></tbody></table></div>`;
 if(page==='surveys') return `<h1>问卷管理</h1><p class="subhead">配置问卷题目、奖励积分和填写统计 <button class="primary" style="float:right;padding:9px 15px">＋ 新建问卷</button></p><div class="panel"><table class="data-table"><thead><tr><th>问卷名称</th><th>有效时间</th><th>状态</th><th>奖励积分</th><th>置顶</th><th>提交人数</th><th>操作</th></tr></thead><tbody><tr><td><b>青年生活方式调查问卷</b></td><td>09.01 - 09.30</td><td><span class="tag green">已发布</span></td><td>100</td><td><span class="tag pink">置顶</span></td><td>386</td><td><span class="mini-link">编辑　统计　导出</span></td></tr><tr><td><b>鄞州青年服务需求调研</b></td><td>08.01 - 08.31</td><td><span class="tag gray">已结束</span></td><td>80</td><td>—</td><td>512</td><td><span class="mini-link">查看统计　导出</span></td></tr></tbody></table></div>`;
 if(page==='points') return `<h1>积分明细</h1><p class="subhead">查询用户积分的每一次变动，支持筛选与导出</p><div class="panel"><div class="table-toolbar"><input class="input" placeholder="手机号 / 用户ID"/><select class="input select"><option>全部来源</option><option>参与活动</option><option>调查问卷</option><option>商品兑换</option></select><button class="primary">查询</button><button class="ghost">导出Excel</button></div><table class="data-table"><thead><tr><th>用户</th><th>变动值</th><th>变动后余额</th><th>来源</th><th>关联业务</th><th>时间</th></tr></thead><tbody><tr><td>刘德华</td><td style="color:#35a878">+100</td><td>1005</td><td><span class="tag blue">调查问卷</span></td><td>青年生活方式调查问卷</td><td>09-12 10:08</td></tr><tr><td>刘德华</td><td style="color:#e56b8f">-100</td><td>905</td><td><span class="tag orange">商品兑换</span></td><td>潮流定制托特帆布包</td><td>09-12 10:12</td></tr><tr><td>王小明</td><td style="color:#35a878">+10</td><td>680</td><td><span class="tag green">参与活动</span></td><td>${activity}</td><td>09-10 15:26</td></tr></tbody></table></div>`;
 if(page==='content') return `<h1>展示内容</h1><p class="subhead">维护小程序首页和服务点展示内容</p><div class="admin-card-grid"><div class="panel"><div class="panel-title">首页横幅 <small>＋ 新增</small></div><div class="event-cover">${activity}</div><p class="muted">已启用 · 排序 1 · 绑定活动</p></div><div class="panel"><div class="panel-title">关于我们 <small>编辑</small></div><div class="about-card" style="height:90px"><b>鄞领π</b><p>青年服务平台介绍内容</p></div><p class="muted">图文内容 · 最后更新 09-08</p></div><div class="panel"><div class="panel-title">服务点信息 <small>编辑</small></div><p style="font-size:13px;line-height:1.9">鄞领π青年人才驿站<br>宁波市鄞州区学府路 1 号<br><span class="tag green">已启用</span></p></div></div>`;
 return '';
}
function setAdmin(page){document.getElementById('admin-screen').innerHTML=adminPage(page);document.getElementById('admin-title').textContent=adminMeta[page];document.querySelectorAll('.admin-link').forEach(x=>x.classList.toggle('active',x.dataset.admin===page))}
document.querySelectorAll('.switch').forEach(x=>x.onclick=()=>{document.querySelectorAll('.switch').forEach(s=>s.classList.remove('active'));x.classList.add('active');document.getElementById('mini-view').classList.toggle('hidden',x.dataset.mode!=='mini');document.getElementById('admin-view').classList.toggle('hidden',x.dataset.mode!=='admin')});
document.querySelectorAll('.page-link,.tab').forEach(x=>x.onclick=()=>setMini(x.dataset.page));
document.querySelectorAll('.admin-link').forEach(x=>x.onclick=()=>setAdmin(x.dataset.admin));
setMini('home');setAdmin('dashboard');
